<?php
/**
 * Created by PhpStorm.
 * User: bvanleeuwen
 * Date: 03/08/16
 * Time: 20:12
 */

namespace bvanleeuwen\checkColumn;

use yii\web\AssetBundle;

class ActiveCheckColumnAsset extends AssetBundle
{
    public $sourcePath = '@vendor/bvanleeuwen/yii2-grid-check-column/assets';

    public $js = [
        'script.action.check.column.js'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}